---
Description: Setup of VPC tester as EC2 instance

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: Select instance size.

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 keypair to enable SSH access to the instance

  SSHCIDR:
    Type: String
    Description: The CIDR block restricting SSH
    MinLength: 9
    Default: 131.247.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x

  USFBucket:
    Type: String
    Description: Contains students and staff key

  USFStudents:
    Type: String
    Description: csv students file in the bucket who can access vpc-tester
  
  USFStaffKey:
    Type: String
    Description: staff pem file in the bucket
   
  USFStaffKeyPwd:
    NoEcho: true
    Type: String    
    Description: staff pem pass phrase
  
Mappings:
  Region2AMI:
    us-east-1: 
      AMI: ami-04505e74c0741db8d 
    us-east-2:
      AMI: ami-0fb653ca2d3203ac1

Resources:
  USFBucketRole: 
    Type: AWS::IAM::Role
    Properties:
      Description: Allows access to secure usf bucket from ec2
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'         
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow           
                Action:
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::${USFBucket}/*'
          PolicyName: USFSecureGetObjects
  VPCTesterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref USFBucketRole            
  VPCTesterInstance:
    Type: AWS::EC2::Instance
    Metadata:
      'AWS::CloudFormation::Authentication':
        S3AccessCreds:
          type: S3
          buckets:
            - !Sub ${USFBucket}          
          roleName: !Ref USFBucketRole
      'AWS::CloudFormation::Init':
          configSets:
            InstallAndRun:
              - Install
              - Install2
          Install:                      
            sources: 
              "/home/ubuntu/vpc": "https://github.com/dvitel/vpnVpcChecker/tarball/master"
            files: 
              "/home/ubuntu/vpc/students.csv": 
                source: !Sub "https://${USFBucket}.s3.amazonaws.com/${USFStudents}"
                group: ubuntu
                owner: ubuntu
                mode: '000600'
                authentication: "S3AccessCreds"
              "/home/ubuntu/vpc/cc.pem": 
                source: !Sub "https://${USFBucket}.s3.amazonaws.com/${USFStaffKey}"
                group: ubuntu
                owner: ubuntu
                mode: '000600'
                authentication: "S3AccessCreds"
              /etc/systemd/system/vpc-tester.service:
                content: !Sub | 
                  [Unit]
                  Description=VPC tester service
                  [Service]
                  User=ubuntu
                  Environment=USF_VPC_PP=${USFStaffKeyPwd}
                  WorkingDirectory=/home/ubuntu/vpc
                  ExecStart=node index.js --server
                  Restart=always
                  [Install]
                  WantedBy=multi-user.target
                mode: '000400'
                owner: root
                group: root    
              /etc/systemd/system/cfn-hup.service:
                content: !Sub |
                  [Unit]
                  Description=cfn-hup daemon
                  [Service]
                  ExecStart=/etc/init.d/cfn-hup -v
                  PIDFile=/var/run/cfn-hup.pid
                  [Install]
                  WantedBy=multi-user.target                                                                                    
              /etc/cfn/cfn-hup.conf:
                content: !Sub |
                  [main]
                  stack=${AWS::StackId}
                  region=${AWS::Region}
                  interval = 5
                mode: '000400'
                owner: root
                group: root
              /etc/cfn/hooks.d/cfn-auto-reloader.conf:
                content: !Sub |
                  [cfn-auto-reloader-hook]
                  triggers=post.update
                  path=Resources.VPCTesterInstance.Metadata.AWS::CloudFormation::Init
                  action=/usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource VPCTesterInstance --configsets InstallAndRun --region ${AWS::Region} 
                  runas=root
                mode: '000400'
                owner: root
                group: root
            commands:
              nodeInstall:
                command: 'curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -'
                cwd: "/home/ubuntu"
                ignoreErrors: false 
          Install2:
            packages:
              apt:
                openvpn: []
                nodejs: []
                ca-certificates: []
                fonts-liberation: []
                libappindicator3-1: []
                libasound2: []
                libatk-bridge2.0-0: []
                libatk1.0-0: []
                libc6: []
                libcairo2: []
                libcups2: []
                libdbus-1-3: []
                libexpat1: []
                libfontconfig1: []
                libgbm1: []
                libgcc1: []
                libglib2.0-0: []
                libgtk-3-0: []
                libnspr4: []
                libnss3: []
                libpango-1.0-0: []
                libpangocairo-1.0-0: []
                libstdc++6: []
                libx11-6: []
                libx11-xcb1: []
                libxcb1: []
                libxcomposite1: []
                libxcursor1: []
                libxdamage1: []
                libxext6: []
                libxfixes3: []
                libxi6: []
                libxrandr2: []
                libxrender1: []
                libxss1: []
                libxtst6: []
                lsb-release: []
                wget: []
                xdg-utils: []
            commands:
              npmInstall:
                command: 'npm install'
                cwd: "/home/ubuntu/vpc"
                ignoreErrors: false 
            services: 
              systemd:
                vpc-tester:
                  enabled: "true"
                  ensureRunning: "true"
                  sources: 
                  - "/home/ubuntu/vpc"
                cfn-hup:
                  enabled: 'true'
                  ensureRunning: 'true'
                  files: 
                    - /etc/cfn/cfn-hup.conf
                    - /etc/cfn/hooks.d/cfn-auto-reloader.conf 
    Properties:
      IamInstanceProfile: !Ref VPCTesterInstanceProfile
      ImageId: !FindInMap [Region2AMI, !Ref 'AWS::Region', 'AMI']
      InstanceType: !Ref InstanceTypeParameter
      SecurityGroups:
      - !Ref VPCTesterSecurityGroup
      Tags:
      - Key: Name
        Value: usf-vpc-tester
      KeyName: !Ref KeyName
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash
          apt-get update
          apt-get -y install python3.8 python3-pip
          python3 -m pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
          ln -s /root/aws-cfn-bootstrap-latest/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
          /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource VPCTesterInstance --configsets InstallAndRun --region ${AWS::Region} 
          /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource VPCTesterInstance --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M          
  VPCTesterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 3001
        ToPort: 3001
        IpProtocol: tcp
      - CidrIp: !Ref SSHCIDR
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
  VPCTesterGateway: 
    Type: AWS::ApiGatewayV2::Api
    Properties: 
      Body:
        openapi: "3.0.1"
        paths:
          "/{proxy+}" :
            parameters: 
              - name: "proxy+"
                in: "path"
                description: "Generated path parameter for proxy+"
                required: true
                schema:
                  type: string
            x-amazon-apigateway-any-method:
              responses:
                default:
                  description: "Default response for ANY /{proxy+}"
              x-amazon-apigateway-integration:
                requestParameters:
                  "overwrite:path": "$request.path"
                payloadFormatVersion: "1.0"
                type: "http_proxy"
                httpMethod: "ANY"
                uri: !Sub "http://${VPCTesterInstance.PublicIp}:3001"
                connectionType: "INTERNET"
    DependsOn: VPCTesterInstance
  VPCTesterGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties: 
      ApiId: !Ref VPCTesterGateway
      AutoDeploy: true
      StageName: $default
        
Outputs:
  InternalURL:
    Description: usf vpc internal http endpoint
    Value: !Sub 'http://${VPCTesterInstance.PublicIp}:3001'
  URL:
    Description: gateway https endpoint
    Value: !Sub ${VPCTesterGateway.ApiEndpoint}